name: Build
on:
  push:
    branches: 'main'
permissions:
  packages: write

jobs:
  build:
    name: GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u luketainton --password-stdin
    - name: Build
      run: docker build . --file Dockerfile --tag ghcr.io/luketainton/documize:latest
    - name: Push
      run: docker push ghcr.io/luketainton/documize:latest
